namespace: otus-hw-6-volodina
replicaCount: 1
image_user_service:
  repository: elenkavolodina/otus_hw5:v9
image_order_service:
  repository: elenkavolodina/otus_hw6:v1
service:
  type: NodePort
  port: 8000
postgresql:
  enabled: true
  postgresqlUsername: root
  postgresqlPassword: root
  postgresqlDatabase: otus
  service:
    port: "5432"