apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://arch.homework/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_6_chart.fullname" . }}
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_6_chart.fullname" . }}
                port:
                  number: 8000

          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_6_chart.fullname" . }}
                port:
                  number: 8000

          - path: /registration
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_6_chart.fullname" . }}
                port:
                  number: 8000

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw_6_chart.fullname" . }}
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://arch.homework/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user_id
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /create_order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8000